version: build.{build}
image: Visual Studio 2017
init:
- cmd: git config --global core.autocrlf true
before_build:
- cmd: >-
    gitversion /l console /output buildserver /updateAssemblyInfo

    nuget restore
build:
  verbosity: minimal
after_build:
- ps: >-
    $nuget_version = "$env:GitVersion_NuGetVersionV2"

    .\.packages\package-NBi-Data3Sixty.ps1 $nuget_version
test_script:
- cmd: nunit-console-x86 /fixture:NBi.Data3Sixty.Testing NBi.Data3Sixty.Testing\bin\debug\NBi.Data3Sixty.Testing.dll
# Use of /fixture and not /run to avoid the Setup
artifacts:
- path: .nupkg\NBi.Data3Sixty.*.nupkg
  name: NBi.Data3Sixty
deploy:
- provider: NuGet
  api_key:
    secure: 7LDAnpfRuEmLf/4hhERYnfy3tHLBqC7wqScUEviYVYkNvrM7C3NN0h73se3QuoNh
  on:
    branch: develop
- provider: NuGet
  api_key:
    secure: 7LDAnpfRuEmLf/4hhERYnfy3tHLBqC7wqScUEviYVYkNvrM7C3NN0h73se3QuoNh
  on:
    APPVEYOR_REPO_TAG: true